spring:
  application:
    name: nbp-api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /api-docs